# Generated by Django 3.2.5 on 2021-07-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('HallowSoup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-write_date']},
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
