# Generated by Django 3.2.9 on 2022-01-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('HallowSoup', '0002_auto_20210710_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='articles', to='HallowSoup.Tag'),
        ),
    ]
