# Generated by Django 3.2.18 on 2023-04-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('HallowSoup', '0003_auto_20220101_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
